version: '3'

services:
  vueapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Map Nginx port 80 to the host's port 8080
    volumes:
      - ./src:/app/src  # Mount the Vue.js source code for live updates during development
    environment:
      - NODE_ENV=development  # Set the environment variable for Vue.js (optional)
